server:
  address: localhost


spring:
  profiles:
    active: @spring.active@

---
spring:
  profiles: dev

server:
  port: 8081

---
spring:
  profiles: test

server:
  port: 8082

---
spring:
  profiles: prod

server:
  port: 8083